import { AnimatedPillar } from "@/components";

export default function Contact() {
  return (
    <>
      {/* <AnimatedPillar /> */}
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
      <div>
        <h1>prueba</h1>
      </div>
    </>
  );
}
